### ISSUE TITLE
[FORGE OPTFINE 19.2 ] Incomplete Fridge/Freeze

### ISSUE THREAD

**Issue by DETOX-ANG** [UnlikePaladin/paladin-furniture-mod#101]
Hi there.

I'm using java 19.2 and I'm having issues with freeze/fridge. It only allows me/ shows the up part. What coud it be?
I don't have the option to use the freeze part

![image](https://github.com/UnlikePaladin/paladins-furniture/assets/34696296/a99ce163-463b-4820-890b-283a6ca137c5)

**Comment by UnlikePaladin** [comment]
we solved this on discord already, fridge and freezer are separate blocks, will be closing the issue now
