### ISSUE TITLE
[1.16.5] Log Spam on Load, Extreme lag when opening workbench UI

### ISSUE THREAD

**Issue by IdrisQe** [UnlikePaladin/paladin-furniture-mod#102]
Minecraft 1.16.5, Forge 36.2.39, Paladin's Furniture 1.2
We added Paladin's Furniture to a modpack we're playing, Infernal Origins v2.0.0 (Patch 2) specifically
(https://www.curseforge.com/minecraft/modpacks/infernal-rpg/files/5045363 for reference)

Issue 1
Upon loading the game with Paladin's, the log is spammed a LOT, to the point where PrismLauncher wouldn't even keep updating the log in realtime. I thought this was because the datapack was generating, but we tried again after it had launched fully, and it happened again anyway.

The host doesn't have the log anymore, but I tried testing it myself. I wasn't able to replicate the on-launch log problem, but was able to quickly make it get extreme by creating and entering a world. It seems like this is an incompatability with Performant's bad loot table detection, judging by the log.

(Had to keep it zipped, it was too large to send otherwise)
[2024-02-18-2.log.gz](https://github.com/UnlikePaladin/paladins-furniture/files/14325743/2024-02-18-2.log.gz)

Issue 2
When opening the Workbench UI, it caused the host's client to freeze completely for 3 seconds every time. No idea the cause. The log doesn't provide any further detail into the cause, but it happens to me too, though it's only around 0.5-1 second(s) each time in my case. 

We both assume this is because of the sheer number of items in the UI... I can't think of how this could be fixed, except maybe using a custom system where you select a base furniture type then provide or select the materials you want, rather than having every possibility load in all at once.

That said, despite the issues, I really love what you've managed with this mod! The dynamic generation, all the options, and even keeping features up-to-date in so many versions of Minecraft! This is a remarkable mod and I'm definitely going to try it in some future modpacks!

**Comment by UnlikePaladin** [comment]
Would need a game log to check why it's being spammed, can't really know without one

**Comment by UnlikePaladin** [comment]
I'll remove the invalid tag if a log is attached but I can't check why it would be spamming or lagging without one

**Comment by IdrisQe** [comment]
Sorry, wasn't done making the post and accidentally sent it far too early. Was getting info from the server host and doing some further testing myself. I've provided my own log now.

**Comment by UnlikePaladin** [comment]
Thanks for the compliments and don't worry! I'm aware of the freezing when opening the workbench, it is indeed because of the sheer number of items being loaded, I do want to see what I can do about that eventually, I want to rewrite the system to be something closer to what you suggested, will definitely check the issues with Performant though, thanks for the report!

**Comment by UnlikePaladin** [comment]
Will be fixed with 1.2.1
