### ISSUE TITLE
The game hangs when loading forge with this mod

### ISSUE THREAD

**Issue by Flowcheer** [UnlikePaladin/paladin-furniture-mod#104]
### Bug Description

I have been trying to play minecraft with this mod, but it just doesnt get over the LOAD_REGISTRIES phase. I have tried deleting other mods to see if it had any incompatibilities or even leaving the mod alone, and it still doesnt work.

### Reproduction Steps

1. Install the mod for forge 1.20.1
2. Game hangs on LOAD_REGISTRIES

### Log File

[latest.log](https://github.com/UnlikePaladin/paladins-furniture/files/14440797/latest.log)
i have been checking the file but i dont see any relevant errors

**Comment by Flowcheer** [comment]
I tried playing the mod on fabric and it works just fine

**Comment by UnlikePaladin** [comment]
Try and update to 1.2.1
