### ISSUE TITLE
[1.18.2] Increased loading times

### ISSUE THREAD

**Issue by esotericdesign** [UnlikePaladin/paladin-furniture-mod#11]
With the mod installed. Minecraft freezes for a few seconds before title screen. Also, with Mod Menu, the game freezes when I press Mods.
Tested with Fabric API 0.58.0 + Cloth Config API 6.4.90, mod versions 1.1.1 and 1.1

**Comment by UnlikePaladin** [comment]
That is just the game loading the mod's assets, I'm working on reducing that anyway but the freeze is not something I can totally fix. If you use Dashloader with the mod it should be faster anyway.

**Comment by esotericdesign** [comment]
DashLoader is now compatible with Sodium, closed

**Comment by UnlikePaladin** [comment]
~_I actually kind of fixed this in the next version anyway, really focused on optimization for it_~
