### ISSUE TITLE
How to get raw Concrete

### ISSUE THREAD

**Issue by Papagei10** [UnlikePaladin/paladin-furniture-mod#114]
### Bug Description

I dont know how to get/make raw concrete

### Reproduction Steps

I just dont know how to get raw concrete

### Log File

As I said i want to know how to get raw concrete

**Comment by voxj** [comment]
First, get Raw Concrete powder by this recipe:
![image](https://github.com/user-attachments/assets/7ee0687e-c97b-4742-b1dc-44bceb93f547)
(upper row and leftest in the middle: Gravel, middle and most right slots in the middle row and bottom row are sand)
Then, put Raw Concrete Powder into Water. Bam, you have Raw Concrete!
