### ISSUE TITLE
(Paladin's Furniture 1.2.1 for Minecraft 1.20.1 - Fabric) When I place particular block from the Mod Server and game Crashing.

### ISSUE THREAD

**Issue by Tark24** [UnlikePaladin/paladin-furniture-mod#137]
### Bug Description

I have a Minecraft server with Fabric 1.20.1 where my friends and I play. I have about 150+ mods... most of them are exploration and build-related mods and library mods. I loved your mod and I installed it on my server but when I craft anything from your mod and when I place that particular table or chair or bed or anything, my server and game crash and every single time I have to run a backup to revive my server if possible try to fix this issue.

Thank you

### Reproduction Steps

I have a Minecraft server where my friends and I play Minecraft. We Love Mods which are related to Decorations, Build and Exploration. When I was Searching for a Furniture Mod with Vanilla Friendly Crafting recipes yet Perfect for Decoration for a House in any SMP, then I came Across this Mod. I had Played a bit in past and it was on FORGE where this mod ran perfectly. I wanted to run the same mod for my SMP which runs on Fabric but when I Installed this mod on the Server as well as on the Client when I tried to Craft any Block from your mod and placed it in the server, It crashed my game and the server, I thought maybe it's server issue so, I created one Creative world in Single Player just to check the Mod and in Creative world game crashed on a same reason.

### Log File

https://mclo.gs/I0G0P1x

**Comment by UnlikePaladin** [comment]
this is a crash on indium's side, not mine
