### ISSUE TITLE
Unable to load worlds

### ISSUE THREAD

**Issue by TomBombTom** [UnlikePaladin/paladin-furniture-mod#14]
I tried adding this mod to my mod folder and decided to play on a super flat world I used for playing around with mods, and the world would not load. I tried with just this mod (paladin-furniture-mod-1.1.1-fabric-mc1.19.jar), and it requirements (fabric-api-0.69.0+1.19.2.jar, cloth-config-8.2.88-fabric.jar), however, I was unable to load into a new world. 
Here is the log:
[latest.log](https://github.com/UnlikePaladin/paladins-furniture/files/10203304/latest.log)

**Comment by UnlikePaladin** [comment]
How much RAM did you allocate to the game, and does this only happen with existing saves or on a new world as well, nothing in the log looks wrong.

**Comment by TomBombTom** [comment]
Nevermind, I allocated 1GB more of RAM (total of 3GB), and it now works
