### ISSUE TITLE
Crash during menu loading 

### ISSUE THREAD

**Issue by Lhyseis** [UnlikePaladin/paladin-furniture-mod#15]
Hello, 

after starting the game, the loading screen have a bugged minecraft "purple and black" texture for a short time then the game crash.
I'm using the latest version of cloth config (cloth-config-9.0.94-forge) and i added your mod to the modpack "All the mods 8" (using forge-43.1.55).

Have a nice day !

[crash-2022-12-16_17.52.07-client.txt](https://github.com/UnlikePaladin/paladins-furniture/files/10247569/crash-2022-12-16_17.52.07-client.txt)

**Comment by UnlikePaladin** [comment]
After looking at the crash log for a bit, nothing in the stacktrace points to my mod, it points to ModelFix so there might be an incompatibility there that I was unaware of, I'll look into what I can do.

**Comment by Lhyseis** [comment]
Thank you for the answer !
Good luck, it's a great mod !

**Comment by Lhyseis** [comment]
I try to add/remove some mods and seems the bug comes from Cloth-config. 
The game load fine with cloth-config-8.2.88 but not with cloth-config-9.0.94

**Comment by brohub-pixel** [comment]
i have the same issue so i was gonna try and do the same but when downloading the last version it says 6.4.90 so like what version exactly did u download? @Lhyseis

**Comment by UnlikePaladin** [comment]
the mod no longer uses or depends on cloth config so this should no longer be an issue
