### ISSUE TITLE
Dying a bed crashes the game :)

### ISSUE THREAD

**Issue by GrandmaPork** [UnlikePaladin/paladin-furniture-mod#19]
I dyed a pink bed light gray, the game crashed and gave me this error: 
Error: java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.blocks.ClassicBed does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.item.DyeColor getColor()' of interface com.unlikepaladin.pfm.blocks.DyeableFurniture.

**Comment by UnlikePaladin** [comment]
Yep, it's a known issue, will fix in the next release!

**Comment by ZAKsPop** [comment]
The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.blocks.ClassicBed does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.item.DyeColor getColor()' of interface com.unlikepaladin.pfm.blocks.DyeableFurniture.

June 16. Still happening. Supposed to be fixed on next release back in January. So when will you update it for 1.19.2 or will you?
