### ISSUE TITLE
No crafting recipes

### ISSUE THREAD

**Issue by GoldenDei** [UnlikePaladin/paladin-furniture-mod#20]
There are no more crafting recipes in the crafting book. Can you tell me what I have to do?

Thank you.

Golden Dei

**Comment by UnlikePaladin** [comment]
The Patchouli book shows how to craft most of the recipes but installing EMI, Just Enough Items and/or Roughly Enough Items can also show you how to make the furniture!

**Comment by GoldenDei** [comment]
Now it is working. Thanks for helping a minecraft starter to have more fun with your great mod in the game.
