### ISSUE TITLE
Some questions about the "drawer"

### ISSUE THREAD

**Issue by lzyzl6** [UnlikePaladin/paladin-furniture-mod#21]
While playing and translating this mod, I noticed the "kitchen wall drawer" and "kitchen wall small drawer" are quite different from the "kitchen drawer".
In fact,they look like "kitchen cabinet" more than "kitchen drawer".
So I once decided to make them translated close to "cabinet",but I failed, for the "kitchen wall drawer"  share the container title with the "kitchen drawer".

Can you tell me what I should do now?
plz  (＠_＠;)

**Comment by lzyzl6** [comment]
And plz have a look at my PR ! 
**CN** translation is **ready** now( if we leave this issue aside )!

**Comment by UnlikePaladin** [comment]
You probably figured it out but yeah, those are getting renamed to cabinet

**Comment by UnlikePaladin** [comment]
I'll close the issue, thanks for the translation again ❤️
