### ISSUE TITLE
config bug

### ISSUE THREAD

**Issue by Kasualix** [UnlikePaladin/paladin-furniture-mod#23]
![image](https://user-images.githubusercontent.com/110756250/212635722-59412e53-060d-43bf-af7a-d912dfd194fa.png)
Mod Version: paladin-furniture-mod-1.1.1-forge-mc1.16.5-patched
Every time I change the "checkForUpdates" to false, the mod still check for updates when I launch my game, and it will also automatically turn into true from false.
![image](https://user-images.githubusercontent.com/110756250/212637727-ddd80243-ec18-487d-bcfc-80e664c5eecd.png)

**Comment by UnlikePaladin** [comment]
That's an oversight on my side, I'll fix it in the next release, thanks for the report

**Comment by UnlikePaladin** [comment]
I've rewritten the mod's config system from the ground up so this shouldn't happen anymore.
