### ISSUE TITLE
Impossible to craft desired Simple Bed variants

### ISSUE THREAD

**Issue by esotericdesign** [UnlikePaladin/paladin-furniture-mod#24]
For some reason, all Simple Beds of Gray and Light Gray colors have the same recipe (bed + 5x Concrete, without wood), which only allows Warped Beds to be crafted. I use Polymorph, but it's no good here, since these are made on Woodworking Table

Mod version: 1.1.1 for Fabric 1.18.2

**Comment by UnlikePaladin** [comment]
Oh god, it's a bug with the recipe generator, I automate the recipes for the most part but I have to hardcode certain things occasionally and it looks like that introduced a bug with the bed recipe. Thanks for the report, I'll fix it in the next version

**Comment by UnlikePaladin** [comment]
Fixed in the next release!
