### ISSUE TITLE
stuck on loading screen, game stops responding (1.19.2 forge)

### ISSUE THREAD

**Issue by clubpenguin1111** [UnlikePaladin/paladin-furniture-mod#25]
I have downloaded the right version of cloth (8.2.88 - 1.19.2) and the right version of Paladin but for some reason it won't load. It freezes at the end of the loading bar and the application stops responding (I have to force quit).
I have tried just loading cloth to see if that was the issue but it loads fine.
I have downloaded every version of the 1.19.2 Forge Paladin's Furniture and still no luck. (One time the game loaded but Paladin's Furniture was not in the mods list) 
I hope there is a fix as I am really looking forward to trying out this mod. 
Thanks.

**Comment by UnlikePaladin** [comment]
You probably didn't allocate enough RAM, the mod's page says you need to give the game a minimum of 4 GB, the default is 2 which isn't enough to load all the assets at once. You can find guides for increasing this value on the internet but I might put one myself together soon, if you need any more assistance feel free to reopen the issue

**Comment by drakosoldier298** [comment]
reopening this as it isnt a ram issue, Many of my players have had this on my modpack, removing paladins furnature fixes it, I reccomend minimum of 4 for our modpack and most players run 8-10.
