### ISSUE TITLE
Light switch causing server lag

### ISSUE THREAD

**Issue by AtlasRiker** [UnlikePaladin/paladin-furniture-mod#28]
Light switches seem to be causing a lag spike every few minutes proceded by the console being filled with the following:

[Server thread/INFO] [STDOUT/]: [com.unlikepaladin.pfm.blocks.blockentities.LightSwitchBlockEntity:func_189515_b:27]: Lights in write:[BlockPos{x=-359, y=75, z=109}, BlockPos{x=-362, y=75, z=109}, BlockPos{x=-362, y=75, z=113}, BlockPos{x=-359, y=75, z=112}, BlockPos{x=-358, y=75, z=114}, BlockPos{x=-356, y=75, z=114}, BlockPos{x=-352, y=75, z=113}, BlockPos{x=-354, y=75, z=110}, BlockPos{x=-354, y=75, z=106}, BlockPos{x=-362, y=81, z=113}, BlockPos{x=-362, y=81, z=109}, BlockPos{x=-359, y=81, z=109}, BlockPos{x=-358, y=81, z=112}, BlockPos{x=-359, y=81, z=114}, BlockPos{x=-354, y=81, z=110}, BlockPos{x=-354, y=81, z=106}, BlockPos{x=-356, y=81, z=113}]

It does this for every single light switch in the world.

version: paladin-furniture-mod-1.1.1-forge-mc1.16.5-patched

**Comment by UnlikePaladin** [comment]
Oops, I might or might not have forgotten to remove the debug code from when I was down porting the light switch to 1.16
