### ISSUE TITLE
Using plate to eat food in bowls deletes bowl

### ISSUE THREAD

**Issue by MarioSMB** [UnlikePaladin/paladin-furniture-mod#31]
Foods with "leftover" items (e.g. bowls from eating stews) are not returned when eating them from a plate.

**Comment by UnlikePaladin** [comment]
Oops lol, I'll have to add some handling for that, I just never considered someone might place that, thanks for the report!

**Comment by UnlikePaladin** [comment]
Fixed in the next release, thanks for the report!  :)
