### ISSUE TITLE
Held item deleted when interacting with furniture

### ISSUE THREAD

**Issue by MarioSMB** [UnlikePaladin/paladin-furniture-mod#32]
It appears as though use actions aren't cancelled out when interacting with the furnishings; for example, if I have a block or item in my hand and right-click a seat of any kind, the block will be deleted, a water bucket in hand will be placed 2 blocks infront of the seat.

Running Forge 1.18.2 if that helps.

**Comment by MarioSMB** [comment]
Occurs in 1.19.2 as well.

**Comment by UnlikePaladin** [comment]
😟

**Comment by Cyimil** [comment]
Also, if you shift-rightclick the furniture from a distance, the lost block will reappear... placed down.

**Comment by UnlikePaladin** [comment]
Well I'm glad to say I fixed the issue, whenever I release 1.3 the fix will be in it. Thanks!
