### ISSUE TITLE
Crashes game

### ISSUE THREAD

**Issue by PeachesLeeches0** [UnlikePaladin/paladin-furniture-mod#34]
Every time I try to join one of my worlds it doesn't load.  Redownloaded everything and checked that they were all up to date, deleted the mod from my file and bam my game was working.

**Comment by Citadis** [comment]
Same problem there
Here is crashlog :
[message (2).txt](https://github.com/UnlikePaladin/paladins-furniture/files/10530240/message.2.txt)

**Comment by UnlikePaladin** [comment]
It appears your configuration file is corrupted. I'll add some handling for this in the future, deleting it might fix it, the config file is under the config directory in your Minecraft instance labelled as pfm.toml

**Comment by ProsperCraft** [comment]
Tag topic [1.19.2][Fabric]

Not having this issue on 1.19.3, Forge
