### ISSUE TITLE
loading screen freezes 

### ISSUE THREAD

**Issue by ThEoqwe** [UnlikePaladin/paladin-furniture-mod#37]
When i get to the launcer i press play and the loading screen comes up and it almost gets done loading then it freezes for forever.
and i use forge 1.19.3

![image](https://user-images.githubusercontent.com/126412426/221427439-761e9557-161f-4363-8722-2722d8ceb12f.png)

mods
![image](https://user-images.githubusercontent.com/126412426/221427474-290e8c52-5ae3-4bbd-a6e4-a40fbea23c91.png)
# #

**Comment by UnlikePaladin** [comment]
Hi, you probably don't have enough RAM allocated to the game, currently the mod needs at least 4GB to properly load all assets. However I'm working on optimizing it for the next version. Here's a guide on how to give the game more RAM. If you need any more help feel free to join my Discord

[https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp](https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp)

**Comment by Tropxical** [comment]
> Hi, you probably don't have enough RAM allocated to the game, currently the mod needs at least 4GB to properly load all assets. However I'm working on optimizing it for the next version. Here's a guide on how to give the game more RAM. If you need any more help feel free to join my Discord
> 
> https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp

Confirmed, allocation of more than 4 GB, will allow everything to load properly.

**Comment by UnlikePaladin** [comment]
Alright, I'm glad to hear it was just that, I'll be closing the issue now.
I've actually reduced RAM usage by a bunch in the next release so it should work with less RAM then, if you need any further assistance with the mod or find any other issues/bugs feel free to open another report!
