### ISSUE TITLE
Basic Cutlery duplicates when used on the bowl

### ISSUE THREAD

**Issue by esotericdesign** [UnlikePaladin/paladin-furniture-mod#38]
self explanatory; tested in SSP, mod version 1.1.1 for Fabric 1.18.2

P.S. another bug I found while building a kitchen is that Classic Stools (Calcite in my case) don't drop themselves, however pickaxe mines them faster; idk if I should open another issue

**Comment by UnlikePaladin** [comment]
Will be fixed in the next release, thanks for the report!
