### ISSUE TITLE
Game not loading with mod installed

### ISSUE THREAD

**Issue by JerRansom** [UnlikePaladin/paladin-furniture-mod#41]
I've tried everything to make the game load with the mod installed, uninstalled other things, changed game settings, and yet it's still sitting about 95% on the loading bar while launching Minecraft, any help would be very appreciated!

**Comment by UnlikePaladin** [comment]
Hi, have you tried allocating at least 4GB of RAM to the game? Currently the mod needs a minimum of 4GB to load all assets, however it's something I'm solving in the next version.
[Guide for allocating more RAM](https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp). If allocating more RAM lets the game load please let me know by closing the issue, but feel free to open a new one if you have any other problems or find any bugs.

**Comment by JerRansom** [comment]
> Hi, have you tried allocating at least 4GB of RAM to the game? Currently the mod needs a minimum of 4GB to load all assets, however it's something I'm solving in the next version. [Guide for allocating more RAM](https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp). If allocating more RAM lets the game load please let me know by closing the issue, but feel free to open a new one if you have any other problems or find any bugs.

Hello, thanks for responding, I've tried that guide that you sent and I still can't get my game to load, It's totally fine if It doesn't work and I'd be completely fine with just waiting for the next update instead of sitting on forums all day whining.

**Comment by 5stigma** [comment]
> Hi, have you tried allocating at least 4GB of RAM to the game? Currently the mod needs a minimum of 4GB to load all assets, however it's something I'm solving in the next version. [Guide for allocating more RAM](https://www.businessinsider.com/guides/tech/how-to-allocate-more-ram-to-minecraft?amp). If allocating more RAM lets the game load please let me know by closing the issue, but feel free to open a new one if you have any other problems or find any bugs.

I have something similar, the mod consumes some ram in 1.18.2 - Forge

**Comment by UnlikePaladin** [comment]
Yeah I know it needs a lot of RAM atm but the issue should be solved in the next version but it still needs some work before I can release it
