### ISSUE TITLE
update 1.19.4[Fabric]

### ISSUE THREAD

**Issue by mrcrashmer** [UnlikePaladin/paladin-furniture-mod#42]
I decided to launch the mod on 1.19.4, but there is nothing new there, although the game works as it should. (Yes, I just did it on the principle that it might work). I looked through the latest news a bit and didn't find anything about updating the mod to 1.19.4, I would like to get it, and not only me, I think the mod has enough fans who are waiting for it :)

**Comment by UnlikePaladin** [comment]
Don't worry about 1.19.4, the thing is I've made many big changes internally, added new blocks, fixed many bugs, heavily optimized the code (the mod is super fast to load now, yay), so what I have on the github is quite different from what's up for download now, but I might release a port of the 1.19.3 version later today :)

**Comment by mrcrashmer** [comment]
It sounds just great, I'm looking forward to it)

**Comment by UnlikePaladin** [comment]
The 1.19.4 port is out now, some stuff got in the way but I'll be closing the issue now, hope you have fun!
