### ISSUE TITLE
[1.1.3][Forge-1.19.4-45.0.40] - mismatched mod channel list

### ISSUE THREAD

**Issue by TigerWalts** [UnlikePaladin/paladin-furniture-mod#44]
Forge: `1.19.4-45-0-40`
Paladin: `1.1.3`
Cloth Config: `10.0.96`
Other mods: None

Not sure why the channel isn't being registered. Maybe the server isn't invoking the NetworkRegistryForge class but the client setup does.

No errors to do with Paladin are observed in the `debug.log`.

**Comment by UnlikePaladin** [comment]
This was fixed in 1.1.4 :)
