### ISSUE TITLE
(1.19.3) Hoppers under microwaves cause a server crash

### ISSUE THREAD

**Issue by hexa0** [UnlikePaladin/paladin-furniture-mod#46]
![Discord_j4TmVGZklX](https://user-images.githubusercontent.com/67880600/236705650-370f117f-1bf5-462e-bb0b-d26443766ebb.png)

[crash-2023-05-07_04.08.33-server.txt](https://github.com/UnlikePaladin/paladins-furniture/files/11416139/crash-2023-05-07_04.08.33-server.txt)

**Comment by UnlikePaladin** [comment]
Known bug, it'll be fixed in the next release, thanks for the report anyway!
