### ISSUE TITLE
Incompatibility with Excalibur Resourcepack

### ISSUE THREAD

**Issue by InteJason** [UnlikePaladin/paladin-furniture-mod#47]
Version: paladin-furniture-mod-1.1.1
Forge: 40.2.1

Simple Beds textures rotation is incorrect, causing the texture to look like this when its used with the excalibur resourcepack:
![2023-05-08_20 50 11](https://user-images.githubusercontent.com/74423341/236951642-75d9f56a-ce44-4aae-bcbe-c0e504377ead.png)
I tried making a resourcepack to override and fix the bed model (path: assets\pfm\models\block\simple_bed\oak\full\simple_bed.json)
But strangely it only overwrote the model as an item within player inventory, but not the block model when its placed.

**Comment by UnlikePaladin** [comment]
Yeah I didn't realize the UVs were a little funky on the foot of the bed, the bed itself is split into foot, and head folders and a full model (only used for item rendering) which is what you overrode, however if you want to fix this manually before I release the next version you'll need to edit the red foot mattress as that is the parent model.
