### ISSUE TITLE
JEI recepies and all recepies don't work when online server

### ISSUE THREAD

**Issue by MikroChris** [UnlikePaladin/paladin-furniture-mod#51]
Hi, I really like your mod, but I have the issue when I first downloaded it, and it's that when I play in a server only the host is able to craft all the new furniture from your mod, and I can't craft any of them, even can't see the recepies from de JEI.

I'd say it's a problem with all the other mods we installed, but I've seen almost 2 coments reporting the same problem but one of them isn't playing with no other mods than JEI.

I really apreciate if you fix this problem, your mod is incredible )=

Also the version I'm playing on is the 1.19.4 and the mod version is 1.1.4 for forge

**Comment by UnlikePaladin** [comment]
There's a problem with the JEI plugin that stops it from working on the server, I'm aware of and looking it. I'll fix it in the next release
