### ISSUE TITLE
Crashing with the new Patchouli update for Minecraft 1.19.4 [Fabric]

### ISSUE THREAD

**Issue by Kojimo** [UnlikePaladin/paladin-furniture-mod#52]
Today after a long time Patchouli for 1.19.4 is out.

Anyway it crashes and gives this error related to Paladin's furniture
Here is the full error log attached below.
[error.txt](https://github.com/UnlikePaladin/paladins-furniture/files/11727694/error.txt)

Thank you.

**Comment by UnlikePaladin** [comment]
Hi, the 1.19.4 version of the mod is ironically incompatible with Patchouli, I updated my mod to 1.19.4 long before they did and they made API breaking changes with no warning that I couldn't account for. I'll fix it in the next release

**Comment by Kojimo** [comment]
Don't worry! It's okay!
We'll wait for the update.
Thanks for your hard work 🙏
