### ISSUE TITLE
[Forge 1.19.4] Crash when loading in singleplayer and multiplayer

### ISSUE THREAD

**Issue by TheDevYellowy** [UnlikePaladin/paladin-furniture-mod#54]
When using Paladin's Furniture (v1.1.4) and Patchouli (v79) the game crashes and I get the following error 

**java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor**

**Comment by Ezequielito1013** [comment]
The same thing happens to me

**Comment by manuelmsni** [comment]
Same to me.
This is the log:

```
The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor.
```

**Comment by HeavenlyRaven** [comment]
The same thing happened to me. The crash is on the client side.

**Comment by UnlikePaladin** [comment]
You'll have to remove Patchouli until I fix this, because I updated long before them to 1.19.4, they made changes to their API that I couldn't account for so it's incompatible with it for the moment. Quite ironic.
