### ISSUE TITLE
NYF's Spiders cause a game crash when they crawl on some furniture like counters

### ISSUE THREAD

**Issue by GrandmaPork** [UnlikePaladin/paladin-furniture-mod#55]
Here's the crash report. Crash didn't happen until I swung at the spider, likely causing it to slightly enter the block

https://pastebin.com/zFGv9bW4

**Comment by UnlikePaladin** [comment]
Looks like it tried to extinguish fire on the spider with the sink's water and it crashed, I'll look into it. Was the sink empty by any chance?

**Comment by GrandmaPork** [comment]
Yes the sink was
