### ISSUE TITLE
Suggestion to remove the recipe for crafting leather

### ISSUE THREAD

**Issue by MightyBunch** [UnlikePaladin/paladin-furniture-mod#59]
You know, usually I don't really like it when functionality is added to a decoration mod. But here I put up with it - everything is quite balanced, and even the rest of the crafts are in the freezer. But leather crafting is just too overpowered. Rotten flash is very easy to get, and leather is always a problem because for this you need to build a separate farm, and you just added a craft from an item that you can farm a stack in one game night. If you do not remove the craft, then at least add the config option. Well, then for all crafts you will have to add an option.

**Comment by UnlikePaladin** [comment]
The mod just like vanilla uses a data pack internally, the format is just like the furnace's so you can just add one that removes the specific recipe you don't like, the id for the rotten flesh leather recipe, which you want to override in this case is rottenflesh_to_leather so under data/pfm/recipes just add an empty json file with that name and the recipe should now be disabled.
