### ISSUE TITLE
Crash when sneak-right clicking a dye kit on a simple bed

### ISSUE THREAD

**Issue by Gronglegrowth** [UnlikePaladin/paladin-furniture-mod#6]
Crash log: [crash-2022-10-04_04.17.14-client.txt](https://github.com/UnlikePaladin/paladins-furniture/files/9704005/crash-2022-10-04_04.17.14-client.txt)

Mod version 1.1.1, for 1.19.2, using Quilt 0.17.4.

**Comment by UnlikePaladin** [comment]
I really thought I'd solved this issue on 1.1, guess I didn't, it's something really minimal, it will be fixed on 1.2, thanks for the report!

**Comment by ProsperCraft** [comment]
Same on 1.19.3 Forge-  I clicked on a double wide bed with a blue dye kit.

https://gist.github.com/ProsperCraft/86202d543b691a06b7a93fe628f01822

paladin-furniture-mod-1.1.2-forge-mc1.19.3
