### ISSUE TITLE
Patchouli guide book not working in 1.20.1 Fabric

### ISSUE THREAD

**Issue by GoldenFurredFox** [UnlikePaladin/paladin-furniture-mod#62]
Paladin's Furniture version 1.2.0-rc3

Patchouli version 1.20.1-81-FABRIC

Guidebook is created but does absolutely nothing upon right click within a server environment when trying to open it from the client

Have not tested in single player at the time of writing, but would presumably behave the same from client to internal server

**Comment by UnlikePaladin** [comment]
Fixed on full 1.2.0
