### ISSUE TITLE
1.16.5 Update checker appears to be crashing our server after boot up

### ISSUE THREAD

**Issue by Zaromas** [UnlikePaladin/paladin-furniture-mod#64]
Right after fully booting up the server crashes with the following message. Crash log attached.

Mod pack: Chroma Endless
Minecraft 1.16.5

Mod pack has worked great for a couple of months, this is brand new. The last PFM update (1.1.1) came out last September, so I am not sure what might have changed.

![image](https://github.com/UnlikePaladin/paladins-furniture/assets/24311186/b5d366b2-3646-4062-a005-da9127dfc1ea)

[crash-2023-11-11_14.43.28-server.txt](https://github.com/UnlikePaladin/paladins-furniture/files/13325866/crash-2023-11-11_14.43.28-server.txt)

**Comment by UnlikePaladin** [comment]
This is weird, could you update the mod to 1.2.0? That should fix it, because there is a new release out that fixes a lot of bugs, adds new blocks and improves loading times, check it on the Modrinth page to download it, CurseForge is having trouble processing files so it will take a few days before it shows up there

**Comment by Zaromas** [comment]
Copy that,will update asap. Just a thought, since the 1.2 update just came out, the version checker just saw it but malfunctioned somehow. The errors say something about font type, any chance there's something in the version checker coding that isn't jiving?

**Comment by UnlikePaladin** [comment]
Yeah, it didn't like something about the text formatting in the update checker, probably used an option that doesn't exist in the server in 1.16 but does in newer version, point is I know what caused the issue and it shouldn't happen again

**Comment by Zaromas** [comment]
Awesome, thank you!

**Comment by silverleaf69** [comment]
I updated to version 1.2 and now my server freezes during startup. I tried to disable the version checker in the config file and it is replaced with the default config file on startup. I would like to set that version checker to false any suggestions on how to fix that so I can continue using the version I am on and not have to update at this moment.

**Comment by Zaromas** [comment]
BTW, that's the guy I run the server with, he took over when I went to work. He says it doesn't even fully boot now, so it doesn't appear to be the update checker anymore (maybe something worse). Should I just remove the mod for.now to see if it is still the mod?

**Comment by UnlikePaladin** [comment]
> I updated to version 1.2 and now my server freezes during startup. I tried to disable the version checker in the config file and it is replaced with the default config file on startup. I would like to set that version checker to false any suggestions on how to fix that so I can continue using the version I am on and not have to update at this moment.

Ironically version 1.2 is the version that allows you to disable the update message, that option was broken on 1.1.x, I reuploaded the mod to fix several critical issues like this one so you should redownload it, and if you're experiencing other issues either join the Discord and ask for assistance or open your own bug report with a game log.

**Comment by UnlikePaladin** [comment]
> BTW, that's the guy I run the server with, he took over when I went to work. He says it doesn't even fully boot now, so it doesn't appear to be the update checker anymore (maybe something worse). Should I just remove the mod for.now to see if it is still the mod?

if it's not fully booting with 1.2 then I'd need a game log with more info on a different Github issue, anyway I just reuploaded the jar so please do check if that reupload fixes the problem.

**Comment by Zaromas** [comment]
Well I just uploaded 1.2 from the Modrinth page and now it's a forge mod loader crash. Crash log attached.
[crash-2023-11-12_02.44.17-fml.txt](https://github.com/UnlikePaladin/paladins-furniture/files/13327025/crash-2023-11-12_02.44.17-fml.txt)

**Comment by Zaromas** [comment]
So I removed the mod altogether and the server is booting up fine. Sucks, because we love the aesthetics in your mod, but gotta play. Please let us know if you find a solution for us.

**Comment by UnlikePaladin** [comment]
Seems the compatibility with CookingForBlockheads is breaking, will put a fix out asap

**Comment by UnlikePaladin** [comment]
the log was super misleading! Found the issue and fixed it

**Comment by UnlikePaladin** [comment]
> So I removed the mod altogether and the server is booting up fine. Sucks, because we love the aesthetics in your mod, but gotta play. Please let us know if you find a solution for us.

Happy to say this is fixed, you can redownload it from Modrinth again, I'm extremely sorry for the inconvenience, long story short in 1.16 a really random function was apparently client only to check for blocks which was causing all these issues, if you encounter any other issues in the future please let me know, I've triple tested it this time so it will work

**Comment by UnlikePaladin** [comment]
While I was at it I also patched the issue that was crashing the update checker so that should never happen again

**Comment by Zaromas** [comment]
We will give it a spin, thank you!!
