### ISSUE TITLE
1.19.2 (Mod Compat issue) Terraqueous Missing furniture textures

### ISSUE THREAD

**Issue by CantWeAllDisagree** [UnlikePaladin/paladin-furniture-mod#69]
![Untitled](https://github.com/UnlikePaladin/paladins-furniture/assets/110773497/2745d9d3-a279-4c64-8782-cd49df4893aa)

All furniture from terraqueous shows up with missing textures, tested with just paladins furniture and terraqueous

https://modrinth.com/mod/terraqueous

**Comment by UnlikePaladin** [comment]
Thanks for the report, I'll put an RP together that you can install that fixes this but it'll be fixed by default in the next mod update!

**Comment by CantWeAllDisagree** [comment]
No worries! It's not a huge issue for me currently, and I'll probably wait for the update. Great work with the rewrite, btw!
