### ISSUE TITLE
X-ray Effect on the corner of some kitchen cabinets

### ISSUE THREAD

**Issue by toastergraphics** [UnlikePaladin/paladin-furniture-mod#7]
When you place the kitchen cabinet in a corner section, it will display an x-ray like effect. this doesn't happen with all of the variants, but if you place different variants of the cabinets next to eachother in a corner shape, it also occurs. This happened to me on the forge version and the fabric version.
![Screen Shot 2022-10-05 at 8 10 04 PM](https://user-images.githubusercontent.com/115128855/194205418-6a7f2519-24ec-44de-a1ab-8ab41b0d3d9f.png)

**Comment by UnlikePaladin** [comment]
Yeah this is a bug that's known to be on 1.1, I forgot to tag the stone variants of the counters and cabinets as not solid/full blocks which causes the issue, thanks for the report, I hadn't noticed it on the cabinets before
