### ISSUE TITLE
[Forge 1.16.5 - Paladin's 1.2] Mod crashes when modded mobs sit on chairs??????

### ISSUE THREAD

**Issue by VickyCute-player** [UnlikePaladin/paladin-furniture-mod#70]
At least that's what the server owner told me, either way Paladin's forced us to update to 1.2.0 and it caused this. This is kinda urgent since the server is crashing every few seconds beyond our control. Below is the crash log! 

Thank you. <3

[crash-2023-11-16_17.18.58-server.txt](https://github.com/UnlikePaladin/paladins-furniture/files/13380760/crash-2023-11-16_17.18.58-server.txt)

**Comment by Karisaholmberg** [comment]
Hi server Owner here, the chair in question I think was one of the log stools, and it even crashed if a player was just in the same area as it. We had to remove the mod to allow player to access the server again.

**Comment by UnlikePaladin** [comment]
Sorry about that, there's a config option for it, I'll disable this behavior by default in the future
