### ISSUE TITLE
[1.20.1 Quilt/Fabric] Incompatible with Cobblemon

### ISSUE THREAD

**Issue by ZaneFlynt01** [UnlikePaladin/paladin-furniture-mod#72]
I wanted to use this mod with the Cobblemon mod, a mod that adds Pokemon to the game. However, every time I try to start the game with both Paladin's Furniture and Cobblemon, it says that the game in unable to load because "directory 'packs' is null."

**Comment by UnlikePaladin** [comment]
Would need a full game log or crash report with more details, I just ran my mod with cobblemon fine on 1.20.1
<img width="966" alt="Screenshot 2023-12-27 at 11 49 26 p m" src="https://github.com/UnlikePaladin/paladins-furniture/assets/36827970/0237242a-09d6-4374-9525-0374c50f7c65">
