### ISSUE TITLE
[1.19.2 Forge] Some items are invisible

### ISSUE THREAD

**Issue by seancrain** [UnlikePaladin/paladin-furniture-mod#77]
When using Paladin's Furniture 1.2.0, several of the furniture blocks appear completely invisible as far as their textures are concerned, but their bounding boxes still show up.

Reverting to 1.1.1 fixes the issue. The issue is present regardless of whether shaders are turned on or not.

The list of mods I have installed can be found here: [https://github.com/Nosiphus/modpack/tree/main/telkit-iv/mods](https://github.com/Nosiphus/modpack/tree/main/telkit-iv/mods)

![2023-12-12_10 18 51](https://github.com/UnlikePaladin/paladins-furniture/assets/38871906/b3af78f8-e94c-4656-a882-46967aa1b8ef)

**Comment by UnlikePaladin** [comment]
some mod is breaking custom baked models, don't really know which one though

**Comment by seancrain** [comment]
I have identified the problem mods as Reforgium and Connectedness, which port the Fabric Rendering API and the Continuity connected textures mod to Minecraft Forge 1.19.2.

**Comment by seancrain** [comment]
That being said, it only happens when you have a connected texture that is set to work on that block. I am working on making test override models that don't use them to see what happens.

**Comment by seancrain** [comment]
This issue is resolved by the model system rewrite of 1.2.1.
