### ISSUE TITLE
Top Texture of Mangrove Log Stool and Inventory Item Texture is Broken

### ISSUE THREAD

**Issue by toastergraphics** [UnlikePaladin/paladin-furniture-mod#8]
![Screen Shot 2022-10-05 at 8 24 36 PM](https://user-images.githubusercontent.com/115128855/194207329-26f1659d-f979-4a09-a1aa-298dcf5c30ec.png)

**Comment by UnlikePaladin** [comment]
I hadn't seen this one, I guess I messed up and deleted the texture at some point, thanks for the report
