### ISSUE TITLE
[1.18.2 Fabric, Paladin's Furniture Version 1.2] Villagers don't sleep anymore.

### ISSUE THREAD

**Issue by ConqAra** [UnlikePaladin/paladin-furniture-mod#81]
Your latest version of paladin's furniture breaks villagers. Using Liberty Villager's Mod debug info, the game considers any village I go to having 0 beds in it even though there's plenty of beds for them to sleep in. I think whatever you did with the bed functionality literally broke villagers being able to sleep in beds. They just can't anymore. Even vanilla beds they don't sleep in.

**Comment by UnlikePaladin** [comment]
I'll need a full mods list, and or a game log, I replace vanilla's point of interest type for Homes with a different one but keep all the existing "workstations" (beds in this case) so this could be a compatibility issue because last I tested it, this works totally fine on my end

**Comment by ConqAra** [comment]
Log with the full modlist: [https://mclo.gs/S9d5T77](https://mclo.gs/S9d5T77)
