### ISSUE TITLE
[1.16.5] Mismatched textures when placing some furniture.  

### ISSUE THREAD

**Issue by Rehasher5** [UnlikePaladin/paladin-furniture-mod#82]
When placing the white/black concrete countertops, the correct item is shown in hand but once placed, it reverts to the oak texture. The sink worked but the counter top and counter top w/ drawers did not. I only tested this type.

I did remove all mods and place them back one by one and it seems like the one that is causing the issue is Twilight Forest. If I remove it, the textures work correctly. As soon as I add it that revert to Oak again.

**Comment by UnlikePaladin** [comment]
I would need a full game log, I ran the game with Twilight Forest and a bunch of other mods on 1.16.5 and it worked fine
