### ISSUE TITLE
1.20.2 missing textures

### ISSUE THREAD

**Issue by potatodragons** [UnlikePaladin/paladin-furniture-mod#83]
on some if the furniture items select parts are using the missing texture colors instead.

**Comment by UnlikePaladin** [comment]
would need more information, like a game log, or a mods list

**Comment by AuraNyxe** [comment]
It's happening to me too. It seems to only be the ones from OTBYG or BOP. I think it's the former. Rainbow Eucalyptus furniture is missing textures, for instance.
