### ISSUE TITLE
Incompatibility with Immersive Portals on 1.18.2

### ISSUE THREAD

**Issue by Zockerhopper** [UnlikePaladin/paladin-furniture-mod#86]
So, I only have Paladin's Furniture mod, version 1.2.0, and Immersive Portals mod, version 1.4.20, turned on and nearly immediately after the game starts, it crashes whiles't trying to load. Note however that if I turn off Immersive Portals the game loads just fine. Here is the the crash report:
[crash-2023-12-30_22.04.19-client.txt](https://github.com/UnlikePaladin/paladins-furniture/files/13799174/crash-2023-12-30_22.04.19-client.txt)

**Comment by Zockerhopper** [comment]
I can confirm that it doesn't work with Immersive Portals 1.4.20-1.4.13 either.

**Comment by UnlikePaladin** [comment]
This is not the full log, I need the latest.log file from that run or a new run where it crashed, that log is actually meaningless

**Comment by Zockerhopper** [comment]
Well, here is the full log: https://mclo.gs/KAOpNvh

**Comment by datzachboi** [comment]
I have the same problem but on 1.19.2
