### ISSUE TITLE
Microwave crash

### ISSUE THREAD

**Issue by WyxZer42** [UnlikePaladin/paladin-furniture-mod#91]
Hi i just placed a microwave and started it with nothing in it and the server crashed and wont restart. Pls help
Im in 1.20.2 Fabric

**Comment by WyxZer42** [comment]
Fixed, Aternos just proposed to kill the microwave entity and now the server work but not eh microwaves

**Comment by WyxZer42** [comment]
My bad, the server won't start up
Here crash log : https://mclo.gs/FxhCJ46

**Comment by EnjoyBacon7** [comment]
Same thing. On Fabric 1.20.2 - Placing Microwave down crashes the server. It does restart however.

**Comment by EnjoyBacon7** [comment]
This was fixed in commit [4bb7abc](https://github.com/UnlikePaladin/paladins-furniture/commit/4bb7abc8e8a9cd869dd57427f089a99730eed960) - waiting for a new version to be released

**Comment by yoboujon** [comment]
Same thing when i started the microwave with nothing in it. It doesn't seems to restart.
