### ISSUE TITLE
Invalid Entries

### ISSUE THREAD

**Issue by soulnot17** [UnlikePaladin/paladin-furniture-mod#92]
Whenever I run my modpack on Modrinth with pfm installed me and my friends would crash all of a sudden and in the logs it says "

[22:26:09] [ForkJoinPool-1-worker-6/WARN]: The mod "pfm" contains invalid entries in its mod json:
--
3 | - Unsupported root entry "modmenu" at line 57 column 12
"

I don't know what it means and I was hoping anyone would have the solution to the fix, heres the full crash log:

https://mclo.gs/6YSoVFT

**Comment by UnlikePaladin** [comment]
A warning is not a crash and my mod is not causing the problem here, I would suspect Puzzle, or some other mod but something just seems to be wrong with your game, there is no crash in the log attached, it just looks like the game shut down
