### ISSUE TITLE
Texture error

### ISSUE THREAD

**Issue by mmmpipi** [UnlikePaladin/paladin-furniture-mod#94]
neoforge47.1.84
Minecraft1.20.1
Added ModernFix，Embeddium
All furniture crafted with wood shows some loss of texture after adding The Twilight Forest Mod.
![2024-01-09_21 22 21](https://github.com/UnlikePaladin/paladins-furniture/assets/153883613/89d43834-fd95-4c84-b91f-788ba5afdc94)

**Comment by UnlikePaladin** [comment]
Will be fixed in 1.2.1
