### ISSUE TITLE
The bathtub is broken at an unusual rate

### ISSUE THREAD

**Issue by mmmpipi** [UnlikePaladin/paladin-furniture-mod#95]
"basic bathtub"Regardless of the tool used, it is slow and shows as indestructible in jade Mod.

**Comment by mmmpipi** [comment]
> “基本浴缸”无论使用什么工具，它都很慢，在翡翠模组中表现出坚不可摧。

Not just the bathtub, but also the cookingtable

**Comment by UnlikePaladin** [comment]
Noted and will be fixed with version 1.2.1, thanks for the report!
