### ISSUE TITLE
(1.20.1)  Broken textures with modded woods

### ISSUE THREAD

**Issue by andres19992** [UnlikePaladin/paladin-furniture-mod#98]
This has been reported before, but I'm still going to give a list of the mods in question as some of them have not been mentioned on the other reports.

Furniture from the following mods have complete or parcial broken textures:
Twilight Forest
Alex's Caves
Aether
Blue Skies

**Comment by ShadowPonyo** [comment]
I think im having the same issue. Some furniture pieces are sowing as purple and black squares, it started after I added blue skies.
